// 미니활동 슬러그 → 짧은 한국어 제목. 학생 활동 이력·교사 통계·결과 화면 등 공통.
// ActivityRenderer 의 displayBlockTitle 와 같은 매핑 — 중앙에서 한 곳만 유지하기 위해 분리.

export const SHORT_ACTIVITY_TITLE: Record<string, string> = {
  "probability_new/mini/rep_perm_password": "비밀번호와 중복순열",
  "probability_new/mini/rep_perm_morse": "모스 부호와 중복순열",
  "probability_new/mini/rep_perm_tiles": "타일 배치와 중복순열",
  "probability_new/mini/rep_perm_dice": "주사위와 중복순열",
  "probability_new/mini/tricolor_flag_perm": "삼색기 순열",
  "probability_new/mini/cube_path_perm": "정육면체 최단경로 순열",
  "probability_new/mini/word_diamond_perm": "단어 다이아몬드 순열",
  "probability_new/mini/rep_comb_stars_bars": "중복조합과 ★｜ 다이어그램",
  "probability_new/mini/poly_expand_term_count": "다항식 전개 항의 개수",
  "probability_new/mini/function_count_lab": "함수 개수 실험실",
  "probability_new/mini/binomial_coeff_viz": "이항계수 시각화",
  "probability_new/mini/binomial_theorem_apply": "이항정리 활용",
  "probability_new/mini/galton_board": "갈튼 보드",
  "probability_new/mini/pascal_triangle_properties": "파스칼 삼각형의 성질",
  "probability_new/mini/morra_game": "손가락 게임 ‘모라’",
  "probability_new/mini/polygon_count_circles": "원 위의 점으로 만든 도형",
  "probability_new/mini/pascal_fractal": "파스칼 삼각형 속 프랙털",
  "probability_new/mini/trial_event_vocab_game": "시행과 사건 용어 마스터",
  "probability_new/mini/weird_dice_sim": "이상한 주사위 — 수학적 확률",
  "probability_new/mini/statistical_prob_sim": "통계적 확률 탐험대",
  "probability_new/mini/stat_prob_experiment": "통계적 확률 실험실",
  "probability/mini/dice_lab": "주사위 실험",
  "probability_new/mini/buffon_needle_mini": "뷔퐁의 바늘 실험",
  "probability_new/mini/bertrand_paradox_mini": "베르트랑의 역설",
  "probability_new/mini/prob_basic_properties": "확률의 기본 성질",
  "probability_new/mini/prob_addition_theorem": "확률의 덧셈정리",
  "probability_new/mini/birthday_paradox_mini": "생일 역설",
  "probability_new/mini/simpsons_paradox_mini": "심슨의 역설",
  "probability/mini/odd_prime_conditional": "홀수일 때 소수일 확률",
  "probability_new/mini/conditional_prob_explorer": "조건부확률 탐험기",
  "probability_new/mini/bayes_theorem_mini": "베이즈 정리 탐구",
  "probability/mini/monty_hall_mini": "몬티홀 시뮬레이터",
  "probability_new/mini/nontransitive_dice": "비추이적 주사위",
  "probability_new/mini/independence_vs_exclusive": "독립과 배반 탐구",
  "probability_new/mini/de_mere_letter": "드 메레의 편지",
  "probability_new/mini/independent_trial_apply": "독립시행 실생활 탐구",
  "probability_new/mini/random_response_survey": "솔직한 설문의 비밀",
  "probability_new/mini/monte_carlo_sim": "몬테카를로 시뮬레이션",
  "probability_new/mini/rv_classify_game": "확률변수 분류 게임",
  "probability_new/mini/distribution_zoo": "세상의 확률분포 한눈에 보기",
  "probability_new/mini/seunggyeongdo_sim": "승경도 윤목 시뮬레이션",
  "probability_new/mini/axb_number_line_lab": "aX+b 수직선 변환 실험실",
  "probability_new/mini/rv_mean_var_lab": "기댓값·분산·표준편차 탐험",
  "probability_new/mini/rv_spreadsheet_lab": "스프레드시트로 확률변수 분석",
  "probability_new/mini/binomial_mean_var_explorer": "이항분포 평균·분산 탐험",
  "probability_new/mini/binomial_graph_sim": "이항분포 그래프 시뮬레이터",
  "probability_new/mini/lln_binomial_simple": "큰 수의 법칙 탐구",
  "probability_new/mini/hardy_weinberg_mini": "하디·바인베르크 법칙",
  "probability_new/mini/normal_compare_p5": "정규분포곡선 비교",
  "probability_new/mini/std_normal_table_quiz": "표준정규분포표 활용 퀴즈",
  "probability_new/mini/binom_normal_approx": "이항분포의 정규 근사",
  "probability_new/mini/census_or_sample_quiz": "전수조사 vs 표본조사 퀴즈",
  "probability_new/mini/random_sampling_lab": "임의추출 방법 시뮬레이션",
  "probability_new/mini/sampling_methods_lab": "복원·비복원·동시추출 실험실",
  "probability_new/mini/pop_sample_mean_lab": "모평균과 표본평균",
  "probability_new/mini/sample_variance_n1_lab": "표본분산을 n−1로 나누는 이유",
  "probability_new/mini/sample_mean_dist_lab": "표본평균의 평균·분산·표준편차",
  "probability_new/mini/sampling_mean_relation_lab": "모평균과 표본평균의 관계",
  "probability_new/mini/ci_confidence_tradeoff_lab": "신뢰도와 구간 길이",
  "probability_new/mini/ci_meaning_lab": "신뢰도의 의미",
  "probability_new/mini/ci_length_factors_lab": "구간 길이의 3가지 요인",
  "probability_new/mini/sample_proportion_dist_lab": "표본비율의 분포",
  "probability_new/mini/ci_proportion_lab": "모비율 신뢰구간 챌린지",
  "probability_new/mini/ci_proportion_news_lab": "뉴스로 배우는 신뢰구간",
  "probability/mini/circular_perm_anchor_p5": "원순열과 한 자리 고정",
  "probability/mini/polygon_edge_arrangements_p5": "다각형 변 위 배열과 대칭",
  "common2/mini/two_point_distance": "두 점 사이의 거리",
  "common2/mini/internal_division_lab": "선분의 내분과 황금비",
  "common2/mini/centroid_lab": "무게중심과 내분",
  "common2/mini/block_stacking_lab": "블록 밀기와 조화급수",
  "common2/mini/line_equation_lab": "직선의 방정식 세우기",
  "common2/mini/two_lines_relation_lab": "두 직선의 위치 관계",
  "common2/mini/point_line_distance_lab": "점과 직선 사이의 거리",
  "common2/mini/parallel_perp_lab": "한 점을 지나는 평행선과 수직선",
  "common2/mini/circle_equation_lab": "원의 방정식",
  "common2/mini/circle_general_form_lab": "원의 방정식의 표준형과 일반형",
  "common2/mini/tangent_axis_circle_lab": "좌표축에 접하는 원",
  "common2/mini/apollonius_circle_lab": "아폴로니오스의 원",
  "common2/mini/circle_line_relation_lab": "원과 직선의 위치 관계",
  "common2/mini/circle_tangent_line_lab": "원의 접선의 방정식",
  "common2/mini/translation_lab": "평행이동",
  "common2/mini/reflection_lab": "대칭이동",
  "common2/mini/line_yx_reflection_lab": "직선 y=x 대칭이동",
  "common2/mini/general_symmetry_lab": "점대칭·선대칭의 일반화",
  "common2/mini/shortest_path_lab": "대칭이동과 최단 거리",
  "common2/mini/tessellation_lab": "테셀레이션",
  "common2/mini/move_card_lab": "이동 카드 놀이",
  "common2/mini/set_notation_lab": "집합의 뜻과 표현",
  "common2/mini/set_game_lab": "SET 카드 놀이",
  "common2/mini/subset_lab": "부분집합과 포함관계",
  "economics/mini/stock_index_lab": "주가지수 탐험",
  "economics/mini/gdp_growth_lab": "GDP와 경제성장률",
  "economics/mini/percentage_point_lab": "퍼센트와 퍼센트포인트",
  "economics/mini/employment_lab": "고용률과 실업률",
  "economics/mini/exchange_rate_lab": "환율 변환과 추이",
  "economics/mini/exchange_impact_lab": "환율 변동과 손익",
  "economics/mini/bigmac_index_lab": "빅맥지수와 물가",
  "economics/mini/exchange_smart_lab": "현명하게 환전하기",
  "economics/mini/tax_lab": "세금의 종류",
  "economics/mini/tax_rates_lab": "세계의 세율과 복지",
  "economics/mini/income_tax_lab": "소득세 계산",
  "economics/mini/corporate_tax_lab": "법인세 계산",
  "economics/mini/vat_lab": "부가가치세 계산",
  "economics/mini/excise_tax_lab": "개별소비세 계산",
  "economics/mini/customs_lab": "관세와 FTA",
  "economics/mini/interest_rate_lab": "여러 가지 이율",
  "economics/mini/simple_interest_lab": "단리의 원리합계",
  "economics/mini/compound_interest_lab": "복리의 원리합계",
  "economics/mini/rule_of_72_lab": "맨해튼의 24달러와 72의 법칙",
  "economics/mini/continuous_compound_lab": "연속복리",
  "economics/mini/installment_savings_lab": "정기 적금의 원리합계",
  "economics/mini/present_value_lab": "현재가치와 할인율",
  "economics/mini/pension_lab": "연금의 종류와 생명연금",
  "economics/mini/budget_life_lab": "수입과 지출을 고려한 금융 생활",
  "economics/mini/production_function_lab": "생산함수",
  "economics/mini/cost_function_lab": "비용함수",
  "economics/mini/demand_supply_lab": "수요함수와 공급함수",
  "economics/mini/demand_forecast_lab": "수요량 예측하기",
  "economics/mini/utility_function_lab": "효용함수",
  "economics/mini/ordinal_cardinal_lab": "효용의 순서와 크기",
  "economics/mini/equilibrium_price_lab": "균형가격의 결정",
  "economics/mini/market_adjust_lab": "시장가격과 균형가격",
  "economics/mini/equilibrium_change_lab": "균형가격의 변화",
  "economics/mini/tax_explorer_lab": "공학도구로 균형 찾기",
  "economics/mini/inflation_lab": "인플레이션과 균형가격",
  "economics/mini/region_lab": "부등식의 영역",
  "economics/mini/system_region_lab": "연립부등식의 영역과 최대·최소",
  "economics/mini/linear_programming_lab": "선형계획법",
  "economics/mini/polygon_region_lab": "다각형과 부등식의 영역",
  "common/mini/perm_comb_growth_race": "순열 vs 조합 — r 증가 레이스",
  "common/mini/poly_sort_game": "항 카드 정렬 게임",
  "common/mini/poly_add_sub_game": "동류항 연결 게임",
  "common/mini/poly_mul_expand": "곱셈 공식 확장 탐구",
  "common/mini/algebra_tile_formulas": "대수막대 곱셈 공식 탐구",
  "common/mini/gelosia_mul": "갤로시아 곱셈 탐구",
  "common/mini/synthetic_div_principle": "조립제법 원리 탐구",
  "common/mini/remainder_same_expressions": "나머지가 같은 식 탐험",
  "common/mini/synthetic_div_spreadsheet": "스프레드시트로 조립제법",
  "common/mini/gelosia_div": "갤로시아 나눗셈 탐구",
  "common/mini/identity_game": "항등식 탐정 게임",
  "common/mini/undefined_coefficients": "미정계수법 탐정 게임",
  "common/mini/power_remainder_booster": "거듭제곱 나머지 부스터",
  "common/mini/factor_candidate_radar": "인수 후보 레이더",
  "common/mini/prime_composite_lock": "소수·합성수 잠금 해제",
  "common/mini/factor_pathfinder_arcade": "인수분해 패스파인더 아케이드",
  "common/mini/complex_number_terms": "복소수 정복! 용어 마스터",
  "common/mini/complex_arithmetic_game": "복소수 계산 배틀",
  "common/mini/imaginary_unit_cycle": "허수단위 i의 순환 탐구",
  "common/mini/negative_sqrt_trap": "음수의 제곱근 함정 탈출",
  "common/mini/conjugate_roots_explorer": "켤레근 탐정단",
  "common/mini/vieta_roots_game": "근과 계수의 관계 탐정단",
  "common/mini/quad_func_equation_explorer": "이차함수·방정식 그래프 탐구",
  "common/mini/quad_line_position_explorer": "이차함수·직선 위치관계 실험실",
  "common/mini/quad_maxmin_explorer": "이차함수의 최대·최소 탐구",
  "common/mini/quad_maxmin_reallife": "이차함수 최대·최소 실생활 탐구",
  "common/mini/quad_bridge_curve_fit": "다리에서 이차함수 찾기",
  "common/mini/cubic_quartic_equation_explorer": "삼·사차방정식 풀이 탐구",
  "common/mini/equation_history_flash": "방정식 해법의 역사",
  "common/mini/omega_law_explorer": "ω-법칙 탐구",
  "common/mini/babylonian_cubic_solver": "바빌로니아인의 방정식 풀이",
  "common/mini/simultaneous_quadratic_quiz": "연립이차방정식 해의 개수 스피드퀴즈",
  "common/mini/linear_ineq_system_explorer": "연립일차부등식 수직선 탐구",
  "common/mini/abs_value_ineq_explorer": "절댓값 부등식 탐구",
  "common/mini/quad_ineq_graph_explorer": "이차부등식과 그래프 탐구",
  "common/mini/quad_ineq_maxmin_reallife": "최댓값 찾기 — 표 vs 수식",
  "common/mini/dice_counting_explorer": "주사위로 경우의 수 탐구",
  "common/mini/addition_multiplication_rule": "합·곱 법칙 판별 챌린지",
  "common/mini/permutation_reallife_explorer": "순열 실생활 탐구",
  "common/mini/permutation_identity_explorer": "순열 등식 탐구",
  "common/mini/combination_reallife_explorer": "조합 실생활 탐구",
  "common/mini/combination_identity_explorer": "조합 등식 탐구",
  "common/mini/combination_application_explorer": "조합 활용 탐구",
  "common/mini/counting_daily_sumin": "경우의 수로 바라본 하루",
  "common/mini/map_coloring_explorer": "지도 색칠 경우의 수",
  "common/mini/matrix_pixel_explorer": "사진 속 행렬 탐험",
  "common/mini/matrix_equality_game": "행렬 상등 탐정 게임",
  "common/mini/matrix_ops_explore": "행렬 연산 탐험",
  "common/mini/matrix_mul_reallife": "행렬 곱셈 실생활 탐구",
  "common/mini/matrix_card_dice_game": "행렬 카드 주사위 게임",
  "common/mini/matrix_cipher_explorer": "행렬 암호 탐구",
  "common/mini/matrix_population_migration": "행렬로 보는 두 도시 인구 이동",

  // ── 영재 ──
  // 단원 ① 기이한 소수
  "gifted/sieve_eratosthenes": "에라토스테네스의 체와 소수정리",
  "gifted/multiplicative_functions": "산술함수와 곱셈함수 탐구",
  "gifted/zeta_explorer": "리만 제타함수 탐험",
  "gifted/zeta_arithmetic": "제타함수와 산술함수의 관계",
  // 단원 ② 시어핀스키·카오스
  "gifted/double_pendulum": "이중진자와 카오스",
  "gifted/lorenz_butterfly": "나비효과와 로렌츠",
  "gifted/lorenz_attractor": "로렌츠 끌개",
  "gifted/fractal_dimensions": "프랙털과 차원 탐구",
  "gifted/sierpinski_props": "시에르핀스키 삼각형의 성질",
  "gifted/chaosgame_address": "카오스 게임과 시에르핀스키",
  "etc/chaosgame": "카오스 게임 (BU)",
  // 단원 ② 의 확통 공유 활동 — gifted slug 에도 동일 짧은 이름.
  "gifted/galton_board": "갈튼 보드",
  "gifted/pascal_triangle_props": "파스칼 삼각형의 성질",
  "gifted/pascal_fractal": "파스칼 삼각형 속 프랙털",
  // 단원 ③ 사진·시선
  "gifted/vanishing_point_draw": "소실점 찾기",
  "gifted/measuring_point_distance": "거리점과 화가까지의 거리",
  "gifted/ambassadors_skull": "대사들의 숨겨진 해골",
  "gifted/perspective_projection": "실제 사물과 그림의 관계식",
  "gifted/harmonic_perspective": "등간격 사물과 조화수열",
  "gifted/trinity_distance": "성삼위일체 인물 거리",
  // 단원 ④ 작도 게임
  "gifted/euclidea_warmup": "작도 몸풀기 게임",
  "gifted/euclidea_tool_steps": "작도 도구 — E값의 이유",
  "gifted/euclidea_bingo": "작도 게임 (빙고)",
};

/** 슬러그 → 한국어 짧은 제목.
 * 매핑에 없으면 경로 마지막 세그먼트를 가독성 있게 변환 (밑줄 → 공백). */
export function shortActivityTitle(slug: string | null | undefined): string {
  if (!slug) return "활동";
  const known = SHORT_ACTIVITY_TITLE[slug];
  if (known) return known;
  // "미니:" 접두어 제거 (옛 형식)
  if (slug.startsWith("미니:")) return slug.replace(/^미니:\s*/, "");
  // 경로 형식(예: "common/mini/matrix_pixel_explorer") — 마지막 세그먼트를 읽기 쉽게
  const lastSegment = slug.split("/").pop() ?? slug;
  return lastSegment.replace(/_/g, " ");
}
