-- 20260623_activity_overviews_seed_prob.sql
-- 활동 개요 시드 — 확률과통계 66개 미니활동.
-- activity_overviews(slug PK) 에 슬러그별 개요를 upsert. 재실행 멱등(overview 갱신).
-- 이후 관리자가 /admin/overviews 에서 직접 수정 가능.
--
-- 적용:  Supabase SQL 에디터에서 실행.
-- 검증:  select count(*) from activity_overviews where slug like 'probability%';

insert into public.activity_overviews (slug, overview, updated_at) values
  ($s$probability_new/mini/rep_perm_password$s$, $ov$자릿수와 사용할 숫자의 개수를 바꿔 가며 만들 수 있는 비밀번호의 경우의 수가 어떻게 변하는지 직접 조작·관찰하고, 중복을 허용하는 경우(중복순열)와 허용하지 않는 경우의 차이를 비교하는 활동.$ov$, now()),
  ($s$probability_new/mini/rep_perm_morse$s$, $ov$점·선 두 기호로 길이가 다른 신호를 만들며 각 자리에 기호를 중복해 쓸 때의 신호 개수를 중복순열로 세고, 기호 종류를 늘리면 경우의 수가 어떻게 달라지는지 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/rep_perm_tiles$s$, $ov$색 타일을 여러 칸에 반복 사용해 배열하면서, 색의 수와 칸 수를 바꿀 때 경우의 수(중복순열)가 어떻게 변하는지 비교·관찰하는 활동.$ov$, now()),
  ($s$probability_new/mini/rep_perm_dice$s$, $ov$주사위를 여러 번 던질 때 나오는 눈의 순서를 중복순열로 세고, 주사위 면의 수와 던지는 횟수를 바꿔 가며 경우의 수 변화를 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/tricolor_flag_perm$s$, $ov$색 띠로 깃발을 만들며 같은 색이 섞일 때 서로 다른 배열의 수를 '같은 것이 있는 순열'로 세는 활동. 실제 국기 사례와 연결해 탐구.$ov$, now()),
  ($s$probability_new/mini/cube_path_perm$s$, $ov$정육면체 겉면을 따라 한 꼭짓점에서 반대편 꼭짓점까지 가는 최단경로의 수를, 방향 이동을 '같은 것이 있는 순열'에 대응시켜 세는 활동.$ov$, now()),
  ($s$probability_new/mini/word_diamond_perm$s$, $ov$글자를 마름모꼴로 배열한 그림에서 위에서 아래로 단어를 읽는 경로의 수를 세며, 같은 것이 있는 순열·경우의 수 세기를 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/rep_comb_stars_bars$s$, $ov$중복조합을 '벽과 칸(stars and bars)', 순서쌍 대응, 부정방정식의 해 세 가지 방법으로 시각화하며 중복조합 공식이 성립하는 이유를 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/poly_expand_term_count$s$, $ov$여러 변수 일차식의 거듭제곱은 중복조합으로, 한 문자 고차식의 거듭제곱은 이항정리로 전개했을 때 서로 다른 항의 개수를 세며 두 방법의 차이를 비교하는 활동.$ov$, now()),
  ($s$probability_new/mini/function_count_lab$s$, $ov$두 집합 사이의 함수를 화살표 그림으로 만들며, 함수·일대일함수·일대일대응 등 조건별 함수의 개수를 순열·조합·중복조합으로 세는 활동.$ov$, now()),
  ($s$probability_new/mini/binomial_coeff_viz$s$, $ov$이항식의 지수를 슬라이더로 바꿔 가며 각 항을 두 문자 중 하나를 고르는 모든 경우로 나열해, 전개식의 계수가 조합의 수로 나타남을 시각적으로 확인하고 계수 퀴즈로 정리하는 활동.$ov$, now()),
  ($s$probability_new/mini/binomial_theorem_apply$s$, $ov$이항정리 전개식에 특정 값을 대입하거나 변형하며 이항계수의 여러 성질(계수의 합, 교대합 등)이 어떻게 도출되는지 직접 확인하고 퀴즈로 정리하는 활동.$ov$, now()),
  ($s$probability_new/mini/galton_board$s$, $ov$구슬을 떨어뜨려 못마다 좌우로 갈라지게 하고 줄 수와 좌우 확률을 조절하며, 최종 분포가 이항분포를 따르고 못의 칸 수가 파스칼 삼각형을 이룸을 관찰하는 활동.$ov$, now()),
  ($s$probability_new/mini/pascal_triangle_properties$s$, $ov$파스칼 삼각형의 칸을 직접 클릭하며 좌우대칭, 파스칼 법칙, 각 행의 합 등 이항계수의 여러 성질을 강조 표시로 탐구하고 퀴즈로 확인하는 활동.$ov$, now()),
  ($s$probability_new/mini/polygon_count_circles$s$, $ov$원 위 등간격 점의 개수를 바꿔 가며 점을 이어 만든 선분·삼각형 등 도형의 개수를 세고, 그 수가 조합의 수이며 표 전체가 파스칼 삼각형을 이룸을 발견하는 활동.$ov$, now()),
  ($s$probability_new/mini/pascal_fractal$s$, $ov$파스칼 삼각형의 각 수를 어떤 수로 나눈 나머지에 따라 색칠하고 나누는 수·배율을 바꿔 가며, 시에르핀스키 삼각형 같은 프랙털 무늬가 나타나는 규칙성을 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/morra_game$s$, $ov$손가락을 내고 합을 맞히는 고대 게임 '모라'를 직접 해 보며, 여러 사람이 낼 때 손가락 합별 경우의 수를 '같은 것이 있는 순열'로 세고 합의 분포와 유리한 전략을 시뮬레이션으로 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/trial_event_vocab_game$s$, $ov$주사위·동전 상황의 퀴즈를 풀며 시행·표본공간·사건·근원사건·배반사건·여사건 등 확률의 기본 용어와 그 관계를 익히는 활동.$ov$, now()),
  ($s$probability_new/mini/weird_dice_sim$s$, $ov$정육면체·정팔면체 등 모양이 다른 주사위를 굴려 면별 상대도수를 이론값과 비교하며, 각 경우가 같은 정도로 일어난다는 수학적 확률의 성립 조건을 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/statistical_prob_sim$s$, $ov$윷놀이·기상예보·야구 타율처럼 수학적 확률로 정하기 어려운 상황을 반복 실험해, 상대도수가 일정한 값에 수렴하는 통계적 확률을 관찰하는 활동.$ov$, now()),
  ($s$probability_new/mini/stat_prob_experiment$s$, $ov$동전·주사위·카드로 사건을 골라 시행 횟수를 늘려 가며 상대도수가 수학적 확률에 가까워지는지 그래프로 비교해 큰 수의 법칙을 확인하는 활동.$ov$, now()),
  ($s$probability/mini/dice_lab$s$, $ov$주사위 한두 개로 홀수·소수·합이 7 등 사건을 골라 반복해 굴리며 경험확률과 이론확률을 히스토그램으로 비교하고, 시행을 늘릴수록 둘이 가까워짐을 체험하는 활동.$ov$, now()),
  ($s$probability_new/mini/buffon_needle_mini$s$, $ov$평행선 위로 바늘을 무작위로 던져 선과 만나는 비율로 원주율을 추정하고, 그 원리(뷔퐁의 바늘)와 몬테카를로 방법을 살펴보는 활동.$ov$, now()),
  ($s$probability_new/mini/bertrand_paradox_mini$s$, $ov$원 안에 무작위로 현을 긋는 방법을 세 가지로 달리 정의해 각각의 확률을 시뮬레이션으로 비교하며, 확률 공간을 어떻게 정하느냐에 따라 답이 달라지는 역설을 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/prob_basic_properties$s$, $ov$확률값이 될 수 있는 수를 판정하고 상황별 사건을 공사건·전사건·일반 사건으로 분류하며, 확률은 0과 1 사이이고 전사건의 확률은 1임을 확인하는 활동.$ov$, now()),
  ($s$probability_new/mini/prob_addition_theorem$s$, $ov$벤다이어그램 슬라이더로 두 사건의 확률과 교집합을 바꿔 가며 합사건의 확률을 구하고, 사건이 배반인지 판정한 뒤 덧셈정리로 계산하는 활동.$ov$, now()),
  ($s$probability_new/mini/birthday_paradox_mini$s$, $ov$사람을 한 명씩 무작위로 입장시키며 생일이 같은 쌍이 생길 확률을 시뮬레이션과 여사건 계산으로 살펴보고, 직관보다 빨리 확률이 높아지는 생일 역설을 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/simpsons_paradox_mini$s$, $ov$부분에서의 우세가 전체에서는 뒤집히는 사례를 단계별로 살펴보고, 슬라이더로 직접 역설을 만들어 보며 숨은 제3의 변수가 미치는 영향을 탐구하는 활동.$ov$, now()),
  ($s$probability/mini/odd_prime_conditional$s$, $ov$주사위를 여러 번 굴려 홀수가 나온 경우 중 소수인 비율을 추정하고, 누적 비율이 이론값에 수렴하는 과정을 관찰하는 조건부확률 실험 활동.$ov$, now()),
  ($s$probability_new/mini/conditional_prob_explorer$s$, $ov$주사위·공·카드 상황에서 두 사건을 직접 골라 각 확률과 조건부확률을 벤다이어그램과 함께 비교하며, 조건의 순서와 독립·배반에 따른 차이를 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/bayes_theorem_mini$s$, $ov$진단 키트·스팸 필터 등 여러 상황에서 슬라이더와 분할표로 사전확률과 새로운 증거로부터 사후확률을 계산하며, 기저확률이 결과에 미치는 영향과 베이즈 정리를 탐구하는 활동.$ov$, now()),
  ($s$probability/mini/monty_hall_mini$s$, $ov$몬티홀 게임을 직접 해 보고 선택을 바꾸는 전략과 유지하는 전략의 승률을 반복 시뮬레이션으로 비교하며, 빈칸 채우기로 일반 공식을 유도하는 조건부확률 활동.$ov$, now()),
  ($s$probability_new/mini/nontransitive_dice$s$, $ov$평균이 같은 세 주사위의 승부를 예상한 뒤 확률의 곱셈정리로 각 대결의 승률을 계산하고, 시뮬레이션으로 가위바위보처럼 순환하는 우열을 확인하는 활동.$ov$, now()),
  ($s$probability_new/mini/independence_vs_exclusive$s$, $ov$두 사건이 배반인지 독립인지 종속인지 분류하는 게임과 시각화를 통해, 배반과 독립의 차이 및 독립의 성질을 구분하는 활동.$ov$, now()),
  ($s$probability_new/mini/de_mere_letter$s$, $ov$도박의 점수 분배 문제를 둘러싼 드 메레와 파스칼의 이야기를 따라가며, 중단된 게임의 상금을 공평하게 나누는 방법을 시뮬레이션과 풀이로 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/independent_trial_apply$s$, $ov$자유투·양궁·날씨 등 상황에서 성공 확률과 시행 횟수, 목표 횟수를 조절하며 독립시행의 확률을 공식으로 계산하고 분포로 비교하는 활동.$ov$, now()),
  ($s$probability_new/mini/random_response_survey$s$, $ov$동전 던지기로 설문지를 무작위로 고르게 하는 무작위 응답 기법을 체험하고, 전체 응답에서 민감한 경험자의 비율을 역으로 추정하는 원리를 독립 사건과 연결해 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/monte_carlo_sim$s$, $ov$동전·주사위의 반복 시행 결과가 이항분포에 수렴하는 모습과 무작위 점으로 원주율을 추정하는 실험을 통해, 독립시행을 반복해 확률을 추정하는 방법을 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/rv_classify_game$s$, $ov$실생활 사례 카드를 보고 그 값이 이산확률변수인지 연속확률변수인지 분류하며, 셀 수 있는 값과 구간의 모든 값을 갖는 변수의 차이를 익히는 게임 활동.$ov$, now()),
  ($s$probability_new/mini/distribution_zoo$s$, $ov$이항분포·정규분포를 비롯한 여러 확률분포 카드를 펼쳐 각 분포의 특징과 실생활 예시를 살펴보며, 교과서에서 다루는 분포가 전체 중 일부임을 조망하는 활동.$ov$, now()),
  ($s$probability_new/mini/seunggyeongdo_sim$s$, $ov$조선시대 윷의 일종인 승경도 윤목을 던진 눈의 합을 확률변수로 정의하고, 확률분포표·기댓값·분산을 단계별로 구하며 시뮬레이션으로 확인하는 활동.$ov$, now()),
  ($s$probability_new/mini/axb_number_line_lab$s$, $ov$데이터에 일정한 수를 곱하고 더하는 변환을 슬라이더로 적용하며, 수직선 위 데이터와 평균·분산이 어떻게 달라지는지 관찰하는 활동.$ov$, now()),
  ($s$probability_new/mini/rv_mean_var_lab$s$, $ov$뽑기·판매 등 상황의 확률분포를 골라 기댓값·분산·표준편차를 단계별로 계산하고, 변수에 곱하고 더하는 변환을 적용해 이 값들이 어떻게 바뀌는지 비교하는 활동.$ov$, now()),
  ($s$probability_new/mini/rv_spreadsheet_lab$s$, $ov$스프레드시트 셀에 수식을 직접 입력하고 채우기 기능으로 표를 완성하며 확률변수의 기댓값·분산·표준편차를 구하고, 변환 공식을 확인하는 활동.$ov$, now()),
  ($s$probability_new/mini/binomial_mean_var_explorer$s$, $ov$이항분포의 시행 횟수와 성공 확률을 슬라이더로 바꿔 평균·분산·표준편차와 그래프 모양의 변화를 관찰하고, 직접 시행하는 시뮬레이션과 실생활 사례로 분석하는 활동.$ov$, now()),
  ($s$probability_new/mini/binomial_graph_sim$s$, $ov$이항분포의 시행 횟수와 성공 확률을 조절해 막대그래프와 확률분포표를 실시간으로 살펴보고, 구간 확률과 분포의 모양·최빈값 등을 분석하는 활동.$ov$, now()),
  ($s$probability_new/mini/lln_binomial_simple$s$, $ov$성공 확률과 허용 오차, 시행 횟수를 조절해 상대도수의 변화를 여러 번 그려 보며, 시행이 많아질수록 상대도수가 확률에 가까워지는 큰 수의 법칙을 시뮬레이션으로 체험하는 활동.$ov$, now()),
  ($s$probability_new/mini/hardy_weinberg_mini$s$, $ov$유전자 빈도를 슬라이더로 바꿔 유전자형 비율을 이항식 전개와 퍼넷 사각형으로 구하고, 세대를 거듭해도 빈도가 유지되는 하디·바인베르크 법칙을 시뮬레이션으로 확인하는 활동.$ov$, now()),
  ($s$probability_new/mini/normal_compare_p5$s$, $ov$평균과 표준편차를 슬라이더로 바꾸며 정규분포 곡선의 위치와 폭이 어떻게 달라지는지 관찰하고, 두 곡선을 나란히 비교해 평균은 위치를, 표준편차는 퍼짐을 결정함을 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/std_normal_table_quiz$s$, $ov$표준정규분포표에서 값을 직접 찾아 읽고, 대칭성과 여사건을 이용해 확률과 z값을 서로 구하는 퀴즈로 표 활용법을 연습하는 활동.$ov$, now()),
  ($s$probability_new/mini/binom_normal_approx$s$, $ov$이항분포 막대그래프와 정규분포 곡선을 겹쳐 보며 정규근사가 가능한 조건을 확인하고, 연속성 보정의 필요성과 효과를 막대 면적으로 비교하는 활동.$ov$, now()),
  ($s$probability_new/mini/census_or_sample_quiz$s$, $ov$여론조사·수명 검사 등 실생활 상황에서 전수조사와 표본조사 중 더 적절한 방법을 고르며, 모집단 크기·비용·파괴조사 같은 선택 기준을 정리하는 퀴즈 활동.$ov$, now()),
  ($s$probability_new/mini/random_sampling_lab$s$, $ov$제비뽑기·난수주사위·난수표·엑셀 함수 네 가지 방법으로 모집단에서 표본을 직접 뽑아 보며, 범위를 벗어나거나 중복된 번호를 다시 뽑는 과정을 통해 임의추출의 원리를 체험하는 활동.$ov$, now()),
  ($s$probability_new/mini/sampling_methods_lab$s$, $ov$공을 직접 뽑아 모든 경우를 나열하며 복원추출·비복원추출·동시추출에서 가능한 표본의 수가 어떻게 달라지는지 비교하고, 상황별로 추출 방법을 구분하는 활동.$ov$, now()),
  ($s$probability_new/mini/pop_sample_mean_lab$s$, $ov$숨겨진 모집단에서 표본을 반복해 뽑아 표본평균의 분포를 쌓아 보며, 고정된 모평균과 표본마다 달라지는 표본평균의 차이를 관찰하는 활동.$ov$, now()),
  ($s$probability_new/mini/sample_variance_n1_lab$s$, $ov$표본의 편차제곱합을 모평균 기준과 표본평균 기준으로 비교하고, n과 n−1로 나눈 추정값을 반복 실험해 모분산에 수렴하는 쪽을 확인하며 표본분산을 n−1로 나누는 이유를 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/sample_mean_dist_lab$s$, $ov$여러 모집단에서 일정 크기의 표본을 뽑거나 모든 경우를 열거해, 표본평균의 평균·분산·표준편차가 모집단 값과 어떤 관계로 수렴하는지 히스토그램으로 확인하는 활동.$ov$, now()),
  ($s$probability_new/mini/sampling_mean_relation_lab$s$, $ov$키·점수 등 모집단에서 표본을 여러 번 뽑아 표본평균들의 분포를 정규곡선과 겹쳐 비교하며, 표본 크기에 따른 분포 변화와 표본평균이 정규분포에 가까워지는 모습을 관찰하는 활동.$ov$, now()),
  ($s$probability_new/mini/ci_confidence_tradeoff_lab$s$, $ov$정규분포 위에서 신뢰도를 유지한 채 구간의 좌우 위치를 움직여 대칭으로 잡을 때 신뢰구간이 가장 짧음을 확인하고, 신뢰도를 높이면 구간이 길어지는 관계를 비교하는 활동.$ov$, now()),
  ($s$probability_new/mini/ci_meaning_lab$s$, $ov$같은 모집단에서 표본을 100세트 뽑아 신뢰구간 100개를 그리고, 모평균을 포함하는 구간이 신뢰도에 가까운 비율로 나오는 모습을 반복 관찰하며 '신뢰도'의 의미를 확인하는 활동.$ov$, now()),
  ($s$probability_new/mini/ci_length_factors_lab$s$, $ov$모표준편차·표본 크기·신뢰도 세 가지를 슬라이더로 바꿔 가며 모평균 신뢰구간의 길이가 각각 어떻게 변하는지 그래프로 비교해, 구간 길이를 결정하는 요인을 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/sample_proportion_dist_lab$s$, $ov$동전·자유투 등 상황에서 표본을 반복해 뽑아 표본비율의 분포를 살펴보며, 그 분포가 정규분포에 가까워지고 평균·분산이 이론값에 수렴함을 확인하는 활동.$ov$, now()),
  ($s$probability_new/mini/ci_proportion_lab$s$, $ov$모비율이 숨겨진 항아리에서 표본을 뽑아 신뢰구간을 만들고 실제 모비율을 포함했는지 확인하며, 여러 번 반복해 명중률이 신뢰도에 가까워짐과 구간 길이가 최대가 되는 경우를 탐구하는 활동.$ov$, now()),
  ($s$probability_new/mini/ci_proportion_news_lab$s$, $ov$실제 여론조사 기사에서 표본비율과 표본 크기를 읽어 모비율 신뢰구간을 단계별로 계산하고, 기사에 적힌 '표본오차'가 오차한계와 같음을 확인하며 여러 조사의 구간을 비교하는 활동.$ov$, now()),
  ($s$probability/mini/circular_perm_anchor_p5$s$, $ov$원형으로 앉은 사람들의 배치를 회전시켜 보며 같은 원배치가 여러 회전 모습으로 보임을 관찰하고, 한 사람을 고정하는 것이 회전 중복을 없애는 것과 같아 원순열의 수가 (n−1)!임을 탐구하는 활동.$ov$, now()),
  ($s$probability/mini/polygon_edge_arrangements_p5$s$, $ov$다각형 변에 놓인 칩의 배열에서 회전·대칭을 같은 것으로 볼지 정해, 같아 보이는 배열의 수를 자동으로 판정하며 대칭을 고려한 경우의 수를 탐구하는 활동.$ov$, now())
on conflict (slug) do update set
  overview = excluded.overview,
  updated_at = now();
